### ISSUE TITLE
unable to compile in ubuntu 14.04.01 LTS

### ISSUE THREAD

**Issue by mcheung63** [jpbarrette/curlpp#21]
/root/Downloads/curlpp>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.2' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 

/root/Downloads/curlpp>make
Making all in src
make[1]: Entering directory '/root/Downloads/curlpp/src'
Making all in utilspp
make[2]: Entering directory '/root/Downloads/curlpp/src/utilspp'
/bin/bash ../../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../include/curlpp  -I../../include   -g  -W -Wall -Werror    -I/usr/include -MT LifetimeLibrary.lo -MD -MP -MF .deps/LifetimeLibrary.Tpo -c -o LifetimeLibrary.lo LifetimeLibrary.cpp
mv -f .deps/LifetimeLibrary.Tpo .deps/LifetimeLibrary.Plo
/bin/bash ../../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../include/curlpp  -I../../include   -g  -W -Wall -Werror    -I/usr/include -MT PrivateMembers.lo -MD -MP -MF .deps/PrivateMembers.Tpo -c -o PrivateMembers.lo PrivateMembers.cpp
mv -f .deps/PrivateMembers.Tpo .deps/PrivateMembers.Plo
/bin/bash ../../libtool --silent  --tag=CXX   --mode=link g++  -g  -W -Wall -Werror    -I/usr/include   -o libutilspp.la -rpath /usr/local/lib LifetimeLibrary.lo PrivateMembers.lo  -lstdc++ -L/usr/lib/x86_64-linux-gnu -lcurl
ar: `u' modifier ignored since`D' is the default (see `U')
make[2]: Leaving directory '/root/Downloads/curlpp/src/utilspp'
Making all in curlpp
make[2]: Entering directory '/root/Downloads/curlpp/src/curlpp'
Making all in internal
make[3]: Entering directory '/root/Downloads/curlpp/src/curlpp/internal'
/bin/bash ../../../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../../include/curlpp  -I../../../include/curlpp -I../../../include/curlpp/internal -I../../../include  -I../  -g  -W -Wall -Werror    -I/usr/include -MT CurlHandle.lo -MD -MP -MF .deps/CurlHandle.Tpo -c -o CurlHandle.lo CurlHandle.cpp
In file included from ../../../include/utilspp/Functors.hpp:27:0,
                 from ../../../include/curlpp/internal/../Types.hpp:34,
                 from ../../../include/curlpp/internal/CurlHandle.hpp:31,
                 from CurlHandle.cpp:25:
../../../include/utilspp/functor/Functor.hpp:57:28: error: expected ‘)’ before ‘<’ token
     Functor(std::shared_ptr<Impl> impl)

**Comment by jpbarrette** [comment]
Thanks for the report. It seems that I merged just a portion of the changes I wanted. Main branch should be alright now, but I'll do some further checks with Fedora and Ubuntu.

**Comment by mcheung63** [comment]
I just checkout the latest source from github, it still have this compile error:

/bin/bash ../../../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../../include/curlpp  -I../../../include/curlpp -I../../../include/curlpp/internal -I../../../include  -I../  -g  -W -Wall -Werror    -I/usr/include -MT CurlHandle.lo -MD -MP -MF .deps/CurlHandle.Tpo -c -o CurlHandle.lo CurlHandle.cpp
CurlHandle.cpp:73:2: error: identifier ‘nullptr’ is a keyword in C++11 [-Werror=c++0x-compat]
  : mException(nullptr)
  ^
In file included from ../../../include/utilspp/Functors.hpp:27:0,
                 from ../../../include/curlpp/internal/../Types.hpp:34,
                 from ../../../include/curlpp/internal/CurlHandle.hpp:31,
                 from CurlHandle.cpp:25:
../../../include/utilspp/functor/Functor.hpp:59:28: error: expected ‘)’ before ‘<’ token
     Functor(std::unique_ptr<Impl> impl) 
                            ^
In file included from ../../../include/utilspp/Functors.hpp:27:0,
                 from ../../../include/curlpp/internal/../Types.hpp:34,
                 from ../../../include/curlpp/internal/CurlHandle.hpp:31,
                 from CurlHandle.cpp:25:
../../../include/utilspp/functor/Functor.hpp:147:10: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
     std::unique_ptr<Impl> mImpl;
          ^
In file included from ../../../include/utilspp/Functors.hpp:27:0,
                 from ../../../include/curlpp/internal/../Types.hpp:34,
                 from ../../../include/curlpp/internal/CurlHandle.hpp:31,
                 from CurlHandle.cpp:25:
../../../include/utilspp/functor/Functor.hpp: In copy constructor ‘utilspp::Functor<R, TList>::Functor(const utilspp::Functor<R, TList>&)’:
../../../include/utilspp/functor/Functor.hpp:52:9: error: class ‘utilspp::Functor<R, TList>’ does not have any field named ‘mImpl’
       : mImpl(functor.mImpl->clone())

**Comment by jpbarrette** [comment]
This is still a problem, reopenning

**Comment by iRajul** [comment]
@mcheung63 How did you compile this source code. I did not find 'configure' file .

**Comment by jpbarrette** [comment]
Yeah, I wasn't sure when I did the repository if I should include the configure file or not. Mostly, the configure file is generated through running the autotools. Just run the autogen.sh script file, it should do the job. 

I'll fix that soon. I want to have the configure file in the repository. It's kind of a hassle to have to run autogen.sh, which requires you to have all autotools to be installed.

**Comment by iRajul** [comment]
@jpbarrette It is working. Thanks!

**Comment by DaemonInformatica** [comment]
I'm looking forward to using this, but I have the same problem as mcheung63.. 
I use autogen.sh to generate a configure. 
I use ./configure to generate a Makefile. 
make returns a metric ton of errors, at the top of which is the error about the "nullptr is a keyword" issue. 

Making all in src
make[1]: Entering directory `/home/matrix/src/C++/curlpp_build/curlpp/src'
Making all in utilspp
make[2]: Entering directory `/home/matrix/src/C++/curlpp_build/curlpp/src/utilspp'
/bin/bash ../../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../include/curlpp  -I../../include   -g  -W -Wall -Werror    -I/include/boost-0 -MT LifetimeLibrary.lo -MD -MP -MF .deps/LifetimeLibrary.Tpo -c -o LifetimeLibrary.lo LifetimeLibrary.cpp
mv -f .deps/LifetimeLibrary.Tpo .deps/LifetimeLibrary.Plo
/bin/bash ../../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../include/curlpp  -I../../include   -g  -W -Wall -Werror    -I/include/boost-0 -MT PrivateMembers.lo -MD -MP -MF .deps/PrivateMembers.Tpo -c -o PrivateMembers.lo PrivateMembers.cpp
mv -f .deps/PrivateMembers.Tpo .deps/PrivateMembers.Plo
/bin/bash ../../libtool --silent  --tag=CXX   --mode=link g++  -g  -W -Wall -Werror    -I/include/boost-0   -o libutilspp.la -rpath /usr/local/lib LifetimeLibrary.lo PrivateMembers.lo  -lstdc++ -L/usr/lib/i386-linux-gnu -lcurl
make[2]: Leaving directory `/home/matrix/src/C++/curlpp_build/curlpp/src/utilspp'
Making all in curlpp
make[2]: Entering directory `/home/matrix/src/C++/curlpp_build/curlpp/src/curlpp'
Making all in internal
make[3]: Entering directory `/home/matrix/src/C++/curlpp_build/curlpp/src/curlpp/internal'
/bin/bash ../../../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../../include/curlpp  -I../../../include/curlpp -I../../../include/curlpp/internal -I../../../include  -I../  -g  -W -Wall -Werror    -I/include/boost-0 -MT CurlHandle.lo -MD -MP -MF .deps/CurlHandle.Tpo -c -o CurlHandle.lo CurlHandle.cpp
CurlHandle.cpp:73:2: error: identifier 'nullptr' is a keyword in C++11 [-Werror=c++0x-compat]
  : mException(nullptr)
  ^
In file included from ../../../include/utilspp/Functors.hpp:27:0,
                 from ../../../include/curlpp/internal/../Types.hpp:34,
                 from ../../../include/curlpp/internal/CurlHandle.hpp:31,
                 from CurlHandle.cpp:25:
../../../include/utilspp/functor/Functor.hpp:59:28: error: expected ')' before '<' token
     Functor(std::unique_ptr<Impl> impl) 
                            ^
In file included from ../../../include/utilspp/Functors.hpp:27:0,
                 from ../../../include/curlpp/internal/../Types.hpp:34,
                 from ../../../include/curlpp/internal/CurlHandle.hpp:31,
                 from CurlHandle.cpp:25:
../../../include/utilspp/functor/Functor.hpp:147:5: error: 'unique_ptr' in namespace 'std' does not name a type
     std::unique_ptr<Impl> mImpl;
     ^
..... 
(The entire output of make is about 5 times longer than this.) I've done some research on the '-Werror=c++0x-compat' flag, and it'd seem that the version of g++ we're using is too new?

**Comment by jpbarrette** [comment]
Alright, can you try with following branch?

distributions-fixes-ubuntu

**Comment by NathanJPhillips** [comment]
That now appears to compile.

**Comment by mcheung63** [comment]
Thanks everyone
